// AUTO-GENERATED by scripts/generateStylePreviewAvailability.mjs
// Source: exports/style-previews/extensions/**
// Do not edit manually.

export const stylePreviewAvailability = {
  "extensions-length-set": {
    "ash": [
      "18",
      "22",
      "24"
    ],
    "beige": [
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "18",
      "22",
      "24"
    ],
    "honey": [
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "18",
      "22",
      "24"
    ]
  },
  "extensions-natural-blend": {
    "ash": [
      "18",
      "22",
      "24"
    ],
    "beige": [
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "18",
      "22",
      "24"
    ],
    "honey": [
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22"
    ]
  },
  "extensions-soft-waves": {
    "ash": [
      "18",
      "22",
      "24"
    ],
    "beige": [
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "18",
      "22",
      "24"
    ],
    "honey": [
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "18",
      "22",
      "24"
    ]
  },
  "extensions-volume-set": {
    "ash": [
      "18",
      "22",
      "24"
    ],
    "beige": [
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "18",
      "22",
      "24"
    ],
    "honey": [
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "18",
      "22",
      "24"
    ]
  }
} as const;
