// AUTO-GENERATED by scripts/generateStylePreviewAvailability.mjs
// Source: exports/style-previews/extensions/**
// Do not edit manually.

export const stylePreviewAvailability = {
  "extensions-bombshell-blowout": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-butterfly-layers": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-glam-density": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-length-set": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-luxe-curl": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-natural-blend": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-rooted-bronde": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-sleek-straight": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-soft-waves": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  },
  "extensions-volume-set": {
    "ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "auburn-velvet": [
      "14",
      "18",
      "22",
      "24"
    ],
    "beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "bright-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "butter-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "caramel-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "champagne": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cherry-cola": [
      "14",
      "18",
      "22",
      "24"
    ],
    "chocolate-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cinnamon-spice": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "cool-chestnut": [
      "14",
      "18",
      "22",
      "24"
    ],
    "copper-glow": [
      "14",
      "18",
      "22",
      "24"
    ],
    "deep-espresso-melt": [
      "14",
      "18",
      "22",
      "24"
    ],
    "espresso": [
      "14",
      "18",
      "22",
      "24"
    ],
    "frosted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "honey": [
      "14",
      "18",
      "22",
      "24"
    ],
    "icy-pearl": [
      "14",
      "18",
      "22",
      "24"
    ],
    "lived-in-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "melted-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "mushroom-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "neutral-gloss": [
      "14",
      "18",
      "22",
      "24"
    ],
    "nordic-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "old-money": [
      "14",
      "18",
      "22",
      "24"
    ],
    "pearl-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-icy": [
      "14",
      "18",
      "22",
      "24"
    ],
    "platinum-smoke": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "rooted-vanilla": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sandy-beige": [
      "14",
      "18",
      "22",
      "24"
    ],
    "shadow-root-blonde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "silver-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-bronde": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smoky-mocha": [
      "14",
      "18",
      "22",
      "24"
    ],
    "smudge-root-ash": [
      "14",
      "18",
      "22",
      "24"
    ],
    "soft-black": [
      "14",
      "18",
      "22",
      "24"
    ],
    "sun-kissed": [
      "14",
      "18",
      "22",
      "24"
    ],
    "vanilla-cream": [
      "14",
      "18",
      "22",
      "24"
    ]
  }
} as const;
