import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join('exports', 'style-previews', 'extensions');

function listDirs(p) {
  if (!fs.existsSync(p)) return [];
  return fs
    .readdirSync(p, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

// Filter availability to only the curated preset/color lists defined in data/stylePreviews.ts.
function readCuratedIds() {
  const tsPath = path.join('data', 'stylePreviews.ts');
  if (!fs.existsSync(tsPath)) return null;
  const ts = fs.readFileSync(tsPath, 'utf8');

  const sliceBetween = (startNeedle, endNeedle) => {
    const s = ts.indexOf(startNeedle);
    if (s === -1) return '';
    const e = ts.indexOf(endNeedle, s);
    if (e === -1) return ts.slice(s);
    return ts.slice(s, e + endNeedle.length);
  };

  const extractIds = (block) => {
    const ids = [];
    const re = /\bid\s*:\s*'([^']+)'/g;
    let m;
    while ((m = re.exec(block))) ids.push(m[1]);
    return Array.from(new Set(ids));
  };

  const presetsBlock = sliceBetween('export const extensionPresets', '];');
  const colorsBlock = sliceBetween('export const extensionColors', '];');
  return {
    presets: extractIds(presetsBlock),
    colors: extractIds(colorsBlock),
  };
}

const curated = readCuratedIds();
const curatedPresets = curated?.presets?.length ? curated.presets : listDirs(ROOT);

const availability = {};
for (const preset of curatedPresets) {
  const presetDir = path.join(ROOT, preset);
  const colorsOnDisk = listDirs(presetDir);
  const curatedColors = curated?.colors?.length ? curated.colors : colorsOnDisk;

  availability[preset] = {};
  for (const color of curatedColors) {
    if (!colorsOnDisk.includes(color)) continue;
    const colorDir = path.join(presetDir, color);
    const lengths = listDirs(colorDir);
    availability[preset][color] = lengths;
  }
}

const out = `// AUTO-GENERATED by scripts/generateStylePreviewAvailability.mjs
// Source: exports/style-previews/extensions/**
// Do not edit manually.

export const stylePreviewAvailability = ${JSON.stringify(availability, null, 2)} as const;
`;

fs.writeFileSync(path.join('data', 'stylePreviewAvailability.ts'), out, 'utf8');
console.log('[generateStylePreviewAvailability] wrote data/stylePreviewAvailability.ts');
