import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join('exports', 'style-previews', 'extensions');

function listDirs(p) {
  if (!fs.existsSync(p)) return [];
  return fs
    .readdirSync(p, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

const presets = listDirs(ROOT);

const availability = {};
for (const preset of presets) {
  const presetDir = path.join(ROOT, preset);
  const colors = listDirs(presetDir);
  availability[preset] = {};
  for (const color of colors) {
    const colorDir = path.join(presetDir, color);
    const lengths = listDirs(colorDir);
    availability[preset][color] = lengths;
  }
}

const out = `// AUTO-GENERATED by scripts/generateStylePreviewAvailability.mjs
// Source: exports/style-previews/extensions/**
// Do not edit manually.

export const stylePreviewAvailability = ${JSON.stringify(availability, null, 2)} as const;
`;

fs.writeFileSync(path.join('data', 'stylePreviewAvailability.ts'), out, 'utf8');
console.log('[generateStylePreviewAvailability] wrote data/stylePreviewAvailability.ts');
